### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by cliffordsnow** [developmentseed/JosmMagicWand#2]
I'm getting the following message "Could not load plugin 'josm_magic_wand'. Delete from preferences?"

Running version 18593 of JOSM and openjdk 17

**Comment by yunica** [comment]
you can try running with java 11, latest versions of java are not compatible with opencv.

**Comment by cliffordsnow** [comment]
JOSM is recommending java 17. I'd like to try the tool but don't want to risk problems with other applications that use Java 17 (LTS) - feel free to close this issue if opencv can't be updated.

**Comment by yunica** [comment]
I just made some changes and tests, I have a preview version with the changes, but I would like some direct feedback, could you please download the[ preview version](https://ds-data-projects.s3.amazonaws.com/josm_magic_wand/josm_magic_wand.jar) and replace it in your plugins folder (`.josm/plugins/`).

**Comment by cliffordsnow** [comment]
I'm getting "Could not load plugin 'josm_magic_wand'."

Error: 00035.261 E: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin josm_magic_wand. Cause: java.lang.reflect.InvocationTargetException. Cause: java.lang.UnsatisfiedLinkError: no opencv_java455 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

I didn't have opencv_java installed so I installed it but got the same error message. opencv-java-4.5.5-5.fc36.x86_64 was installed on my system.

**Comment by adamfranco** [comment]
I have the same issue: I am interested in trying out this plugin, but it won't load on newer Java. I'm on an arm-based Mac (Apple M1 processor) and have had a lot of trouble getting set up with a stable Java environment that supports the various applications I need to run, so forward compatibility feels important to me.

**Comment by Atrate** [comment]
If anyone else is having this issue on Flatpak, it can be because of not enough space in Flatpak's isolated `/tmp` dir. Can be fixed by doing: `flatpak override --user --filesystem=/tmp org.openstreetmap.josm`
